# Generated by Django 4.2.11 on 2024-04-06 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("diets", "0001_initial"),
        ("diets", "0002_daysoftheweek_delete_dayoftheweek_diettable_day_id"),
        ("diets", "0003_mealtable_mealnumber_id"),
        ("diets", "0004_remove_mealtable_mealnumber_id_and_more"),
        ("diets", "0005_rename_mealfoodtable_groupmealtable_and_more"),
        ("diets", "0006_rename_meal_id_groupmealtable_meal_id_1_and_more"),
        ("diets", "0007_groupmealtable_meal_id_3_and_more"),
        ("diets", "0008_groupmealtable_meal_id_10_groupmealtable_meal_id_4_and_more"),
        ("diets", "0009_remove_diettable_day_id"),
        ("diets", "0010_alter_daysoftheweek_mealfood_id"),
        ("diets", "0011_alter_daysoftheweek_mealfood_id"),
        ("diets", "0012_groupmealtable_diet_id"),
        ("diets", "0013_rename_mealnumber_id_groupmealtable_mealnumberoftheday"),
        ("diets", "0014_remove_daysoftheweek_mealoftheday"),
        ("diets", "0015_rename_mealfood_id_daysoftheweek_mealfood_one_and_more"),
        ("diets", "0016_alter_diettable_startdate"),
        ("diets", "0017_alter_diettable_startdate"),
        ("diets", "0018_alter_diettable_startdate"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietTable",
            fields=[
                ("diet_id", models.AutoField(primary_key=True, serialize=False)),
                ("dietName", models.CharField(max_length=50)),
                ("startDate", models.DateTimeField()),
                ("dayLength", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DietTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dietType", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="FoodTable",
            fields=[
                ("food_id", models.AutoField(primary_key=True, serialize=False)),
                ("foodName", models.CharField(max_length=20)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("proteins", models.FloatField(blank=True, null=True)),
                ("carbohydrates", models.FloatField(blank=True, null=True)),
                ("fats", models.FloatField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDietsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.diettable",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SingleMealRowTable",
            fields=[
                ("meal_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "food_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diets.foodtable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diettable",
            name="dietType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="diets.diettypes"
            ),
        ),
        migrations.CreateModel(
            name="GroupMealTable",
            fields=[
                ("mealFood_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "meal_id_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.mealtable",
                    ),
                ),
                ("mealNumberOfTheDay", models.IntegerField(default=-1)),
                (
                    "meal_id_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_2",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_3",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_10",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_4",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_5",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_6",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_7",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_8",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_8",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "meal_id_9",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_9",
                        to="diets.singlemealrowtable",
                    ),
                ),
                (
                    "diet_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.diettable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DaysOfTheWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_id", models.IntegerField(default="", null=True)),
                (
                    "diet_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.diettable",
                    ),
                ),
                (
                    "mealFood_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diets.groupmealtable",
                    ),
                ),
                (
                    "mealFood_five",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_5",
                        to="diets.groupmealtable",
                    ),
                ),
                (
                    "mealFood_four",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_4",
                        to="diets.groupmealtable",
                    ),
                ),
                (
                    "mealFood_three",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_3",
                        to="diets.groupmealtable",
                    ),
                ),
                (
                    "mealFood_two",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requests_2",
                        to="diets.groupmealtable",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="diettable",
            name="startDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="diettable",
            name="startDate",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="diettable",
            name="startDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
