# Generated by Django 4.0.4 on 2022-05-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DietTable',
            fields=[
                ('diet_id', models.AutoField(primary_key=True, serialize=False)),
                ('dietName', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField()),
                ('dayLength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DietTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=20)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDietsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.diettable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealTable',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diets.foodtable')),
            ],
        ),
        migrations.CreateModel(
            name='MealFoodTable',
            fields=[
                ('mealFood_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.mealtable')),
            ],
        ),
        migrations.AddField(
            model_name='diettable',
            name='dietType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diets.diettypes'),
        ),
    ]
