# Generated by Django 4.0.4 on 2022-05-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(default='', null=True)),
                ('mealOfTheDay', models.IntegerField()),
                ('diet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.diettable')),
                ('mealFood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.mealfoodtable')),
            ],
        ),
        migrations.DeleteModel(
            name='DayOfTheWeek',
        ),
        migrations.AddField(
            model_name='diettable',
            name='day_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.daysoftheweek'),
        ),
    ]
