# Generated by Django 4.0.4 on 2022-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_daysoftheweek_delete_dayoftheweek_diettable_day_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtable',
            name='mealNumber_id',
            field=models.IntegerField(default=-1),
        ),
    ]
