# Generated by Django 4.0.4 on 2022-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_mealtable_mealnumber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtable',
            name='mealNumber_id',
        ),
        migrations.AddField(
            model_name='mealfoodtable',
            name='mealNumber_id',
            field=models.IntegerField(default=-1),
        ),
    ]
