# Generated by Django 4.0.4 on 2022-05-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_rename_mealfoodtable_groupmealtable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmealtable',
            old_name='meal_id',
            new_name='meal_id_1',
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='diets.singlemealrowtable'),
        ),
    ]
