# Generated by Django 4.0.4 on 2022-05-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_groupmealtable_meal_id_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_10', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_4', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_5', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_6', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_7', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_8', to='diets.singlemealrowtable'),
        ),
        migrations.AddField(
            model_name='groupmealtable',
            name='meal_id_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_9', to='diets.singlemealrowtable'),
        ),
    ]
