# Generated by Django 4.0.4 on 2022-05-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_alter_daysoftheweek_mealfood_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoftheweek',
            name='mealFood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.groupmealtable'),
        ),
    ]
