# Generated by Django 4.0.4 on 2022-05-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_alter_daysoftheweek_mealfood_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmealtable',
            name='diet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.diettable'),
        ),
    ]
