# Generated by Django 4.0.4 on 2022-05-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_groupmealtable_diet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmealtable',
            old_name='mealNumber_id',
            new_name='mealNumberOfTheDay',
        ),
    ]
