# Generated by Django 4.0.4 on 2022-05-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0013_rename_mealnumber_id_groupmealtable_mealnumberoftheday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysoftheweek',
            name='mealOfTheDay',
        ),
    ]
