# Generated by Django 4.0.4 on 2022-05-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0014_remove_daysoftheweek_mealoftheday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysoftheweek',
            old_name='mealFood_id',
            new_name='mealFood_one',
        ),
        migrations.AddField(
            model_name='daysoftheweek',
            name='mealFood_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_5', to='diets.groupmealtable'),
        ),
        migrations.AddField(
            model_name='daysoftheweek',
            name='mealFood_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_4', to='diets.groupmealtable'),
        ),
        migrations.AddField(
            model_name='daysoftheweek',
            name='mealFood_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_3', to='diets.groupmealtable'),
        ),
        migrations.AddField(
            model_name='daysoftheweek',
            name='mealFood_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_2', to='diets.groupmealtable'),
        ),
    ]
