# Generated by Django 4.0.4 on 2022-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0015_rename_mealfood_id_daysoftheweek_mealfood_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diettable',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
