# Generated by Django 4.0.4 on 2022-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0016_alter_diettable_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diettable',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
